---
- name: Health Check HTML Report
  hosts: all
  become: true
  gather_facts: true
  strategy: linear
  vars:
    disk_threshold: 80
    mem_threshold: 170000
    load_threshold: 2.0
    email_to: "admin@example.com"
    report_base_path: "/tmp/healthcheck_reports/"
  pre_tasks:
    - name: Create report directory
      ansible.builtin.file:
        path: "{{ report_base_path }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      become: false

  tasks:
    - name: Find old reports
      ansible.builtin.find:
        paths: "{{ report_base_path }}"
        patterns: "report_*.html"
        file_type: file
      delegate_to: localhost
      become: false
      register: find_result

    - name: Remove old reports
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ find_result.files }}"
      delegate_to: localhost
      become: false

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
      become: true
      changed_when: false

    - name: Set report timestamp
      ansible.builtin.set_fact:
        report_timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
      delegate_to: localhost

    - name: Gather information from hosts
      block:
        - name: Gather firmware information
          ansible.builtin.command: dmidecode -t bios
          become: true
          register: firmware_info
          changed_when: false
          failed_when: false

        - name: Set firmware facts
          ansible.builtin.set_fact:
            firmware_details: "{{ firmware_info.stdout_lines | default(['N/A']) }}"

        - name: Collect disk usage
          ansible.builtin.command: df -h /
          register: disk_used
          changed_when: false

        - name: Set Memory fact
          ansible.builtin.set_fact:
            mem_free_mb: "{{ ansible_memory_mb.real.free }}"

        - name: Get Timezone info
          ansible.builtin.command: timedatectl
          register: timezone_info
          changed_when: false

        - name: Get list of running services
          ansible.builtin.service_facts:
          register: running_services
          changed_when: false

        - name: Filter running services
          ansible.builtin.set_fact:
            running_services_list: "{{ services | dict2items | selectattr('value.state', 'equalto', 'running') | list }}"
          changed_when: false

        - name: Filter failed services
          ansible.builtin.set_fact:
            failed_services_list: "{{ services | dict2items | selectattr('value.state', 'equalto', 'failed') | list }}"
          changed_when: false

        - name: Get journalctl error logs
          ansible.builtin.command: journalctl -p 3 -xb -n 20
          register: error_logs
          changed_when: false

        - name: Get list of logrotate configured services
          ansible.builtin.find:
            paths: /etc/logrotate.d
            file_type: file
          register: logrotate_services
          changed_when: false

        - name: Set logrotate services fact
          ansible.builtin.set_fact:
            logrotate_services_fact: "{{ logrotate_services.files | map(attribute='path') | map('basename') | list }}"

        - name: Get all pods in all namespaces
          ansible.builtin.command: kubectl get pods -A
          register: all_pods
          changed_when: false
          failed_when: false

        - name: Get non-running pods
          ansible.builtin.command: kubectl get pods -A --field-selector=status.phase!=Running
          register: non_running_pods
          changed_when: false
          failed_when: false

        - name: Get pods with 0/ readiness
          ansible.builtin.shell: "set -o pipefail && kubectl get pods -A | grep '0/'"
          register: zero_ready_pods
          changed_when: false
          failed_when: false

        - name: Set zero ready pods fact
          ansible.builtin.set_fact:
            zero_ready_pods_fact: "{{ zero_ready_pods.stdout }}"

        - name: Get events with Warnings
          ansible.builtin.command: kubectl get events --all-namespaces --field-selector=type=Warning
          register: warnings
          changed_when: false
          failed_when: false

        - name: Get top pods by CPU
          ansible.builtin.command: kubectl top pods -A --sort-by=cpu
          register: top_pods_cpu
          changed_when: false
          failed_when: false

        - name: Set top pods CPU fact
          ansible.builtin.set_fact:
            top_pods_cpu_fact: "{{ top_pods_cpu.stdout }}"

        - name: Get top nodes by CPU
          ansible.builtin.command: kubectl top nodes --sort-by=cpu
          register: top_nodes_cpu
          changed_when: false
          failed_when: false

      rescue:
        - name: Handle errors
          ansible.builtin.debug:
            msg: "An error occurred on {{ inventory_hostname }}"

    - name: Ensure logrotate service is enabled and running (RedHat)
      ansible.builtin.systemd:
        name: logrotate.timer
        state: started
        enabled: true
      failed_when: false

    - name: Generate report
      ansible.builtin.template:
        src: templates/report.html.j2
        dest: "{{ report_base_path }}/report_{{ inventory_hostname }}_{{ report_timestamp }}.html"
        mode: "0600"
      delegate_to: localhost
      become: false
      register: report_files

    - name: Create zip archive of all reports
      community.general.archive:
        path: "{{ report_base_path }}/report_*.html"
        dest: "{{ report_base_path }}/healthcheck_reports_{{ report_timestamp }}.zip"
        format: zip
        mode: "0600"
      delegate_to: localhost
      become: false
      failed_when: false

    - name: Clean up individual report files
      ansible.builtin.file:
        path: "{{ report_base_path }}/report_*.html"
        state: absent
      delegate_to: localhost
      become: false
