---
- name: Health Check HTML Report
  hosts: all
  become: true
  gather_facts: yes
  vars:
    disk_threshold: 80
    mem_threshold: 170000
    load_threshold: 2.0
    email_to: "admin@example.com"
  tasks:
    - name: Gather information from hosts
      block:
        - name: Collect disk usage
          shell: df -h / | awk 'NR==2{print $5}' | tr -d '%'
          register: disk_used
          changed_when: false

        - name: Set Memory fact
          set_fact:
            mem_free_mb: "{{ ansible_memory_mb.real.free }}"

        - name: Get Timezone info
          shell: timedatectl | grep "Time zone" | awk '{print $3}'
          register: timezone_info
          changed_when: false

        - name: Get NTP Server info
          shell: ntpq -p | grep -v Name
          register: ntp_info
          changed_when: false

        - name: Get list of running services
          shell: "systemctl list-units --type=service --state=running | grep -v -E 'LOAD|ACTIVE|SUB|loaded units listed'"
          register: running_services
          changed_when: false

        - name: Get list of failed services
          shell: "systemctl list-units --type=service --state=failed | grep -v -E 'LOAD|ACTIVE|SUB|loaded units listed'"
          register: failed_services
          changed_when: false

        - name: Get journalctl error logs
          shell: "journalctl -p 3 -xb -n 20"
          register: error_logs
          changed_when: false

        - name: Get all pods in all namespaces
          shell: "kubectl get pods -A"
          register: all_pods
          ignore_errors: true

        - name: Get non-running pods
          shell: "kubectl get pods -A | grep -v Running"
          register: non_running_pods
          ignore_errors: true

        - name: Get pods with 0/ readiness
          shell: "kubectl get pods -A | grep '0/' | true"
          register: zero_ready_pods
          ignore_errors: true

        - name: Set zero ready pods fact
          set_fact:
            zero_ready_pods_fact: "{{ zero_ready_pods.stdout }}"

        - name: Get events with Warnings
          shell: "kubectl get events --all-namespaces | grep Warning"
          register: warnings
          ignore_errors: true

        - name: Get top pods by CPU
          shell: "kubectl top pods -A --sort-by=cpu | head -10"
          register: top_pods_cpu
          ignore_errors: true

        - name: Set top pods CPU fact
          set_fact:
            top_pods_cpu_fact: "{{ top_pods_cpu.stdout }}"

        - name: Get top nodes by CPU
          shell: "kubectl top nodes --sort-by=cpu | head -10"
          register: top_nodes_cpu
          ignore_errors: true

      rescue:
        - name: Handle errors
          debug:
            msg: "An error occurred on {{ inventory_hostname }}"

    - name: Generate report
      template:
        src: templates/report.html.j2
        dest: "/tmp/report_{{ inventory_hostname }}.html"
        mode: "0600"
      delegate_to: localhost